[tool.poetry]
name = "yais"
version = "0.2.6"
description = "Yet Another Image Scraper"
authors = ["Wu Haotian <whtsky@gmail.com>"]
license = "MIT"
readme = "README.md"

repository = "https://github.com/whtsky/yais"


[tool.poetry.dependencies]
python = "^3.7"
imagesize = "^1.2.0"
requests = "^2.24.0"
beautifulsoup4 = "^4.8.1"
appdirs = "^1.4.4"
cloudscraper = "^1.2.48"

[tool.poetry.dev-dependencies]
black = "^19.3b0"
pytest = "^6.1.1"
pytest-cov = "^2.10.1"
mypy = "^0.740"
responses = "^0.12.0"

[tool.poetry.scripts]
yais = "yais:cli"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

