[tool.poetry]
name = "yais"
version = "0.2.3"
description = "Yet Another Image Scraper"
authors = ["Wu Haotian <whtsky@gmail.com>"]
license = "MIT"
readme = "README.md"

repository = "https://github.com/whtsky/yais"


[tool.poetry.dependencies]
python = "^3.7"
imagesize = "^1.1.0"
requests = "^2.22.0"
beautifulsoup4 = "^4.8.1"

[tool.poetry.dev-dependencies]
black = "^19.3b0"
pytest = "^5.3.2"
pytest-cov = "^2.8.1"
mypy = "^0.740"
responses = "^0.10.9"

[tool.poetry.scripts]
yais = "yais:cli"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

